export const mockProducts = [
  // Men's Clothing (6 productos)
  {
    id: 1,
    title: 'Camiseta Urbana de Algodón',
    price: 19.99,
    description: 'Una camiseta cómoda y moderna para uso diario con corte relajado.',
    category: "men's clothing",
    image: 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg',
    rating: { rate: 4.3, count: 110 },
  },
  {
    id: 2,
    title: 'Zapatillas Deportivas',
    price: 55.5,
    description: 'Zapatillas ligeras y resistentes pensadas para entrenamiento y paseo.',
    category: "men's clothing",
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    rating: { rate: 4.1, count: 90 },
  },
  {
    id: 3,
    title: 'Pantalón Chino Clásico',
    price: 42.99,
    description: 'Pantalón de algodón con corte recto perfecto para oficina o casual.',
    category: "men's clothing",
    image: 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg',
    rating: { rate: 4.5, count: 85 },
  },
  {
    id: 4,
    title: 'Chaqueta de Cuero Sintético',
    price: 89.99,
    description: 'Chaqueta moderna con forro interior y múltiples bolsillos.',
    category: "men's clothing",
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    rating: { rate: 4.6, count: 120 },
  },
  {
    id: 5,
    title: 'Sudadera con Capucha',
    price: 34.99,
    description: 'Sudadera cómoda de algodón orgánico con diseño minimalista.',
    category: "men's clothing",
    image: 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg',
    rating: { rate: 4.2, count: 95 },
  },
  {
    id: 6,
    title: 'Zapatos Formales',
    price: 79.99,
    description: 'Zapatos de cuero sintético ideales para ocasiones formales.',
    category: "men's clothing",
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    rating: { rate: 4.4, count: 75 },
  },

  // Women's Clothing (6 productos)
  {
    id: 7,
    title: 'Bolso Casual para Mujer',
    price: 34.0,
    description: 'Bolso moderno con varios compartimentos y cierre seguro.',
    category: "women's clothing",
    image: 'https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg',
    rating: { rate: 4.0, count: 70 },
  },
  {
    id: 8,
    title: 'Vestido Floral',
    price: 39.95,
    description: 'Vestido ligero con estampado floral ideal para temporada de verano.',
    category: "women's clothing",
    image: 'https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg',
    rating: { rate: 4.2, count: 95 },
  },
  {
    id: 9,
    title: 'Blusa de Seda',
    price: 29.99,
    description: 'Blusa elegante de seda natural con cuello en V.',
    category: "women's clothing",
    image: 'https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg',
    rating: { rate: 4.3, count: 110 },
  },
  {
    id: 10,
    title: 'Falda Plisada',
    price: 24.99,
    description: 'Falda plisada midi con tela ligera y cómoda.',
    category: "women's clothing",
    image: 'https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg',
    rating: { rate: 4.1, count: 85 },
  },
  {
    id: 11,
    title: 'Abrigo de Lana',
    price: 119.99,
    description: 'Abrigo elegante de lana merino para invierno.',
    category: "women's clothing",
    image: 'https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg',
    rating: { rate: 4.7, count: 65 },
  },
  {
    id: 12,
    title: 'Sandalias de Verano',
    price: 19.99,
    description: 'Sandalias cómodas con plataforma baja para uso diario.',
    category: "women's clothing",
    image: 'https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg',
    rating: { rate: 4.0, count: 140 },
  },

  // Electronics (6 productos)
  {
    id: 13,
    title: 'Auriculares Inalámbricos',
    price: 45.75,
    description: 'Auriculares bluetooth con cancelación de ruido y batería de larga duración.',
    category: 'electronics',
    image: 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg',
    rating: { rate: 4.6, count: 200 },
  },
  {
    id: 14,
    title: 'Mochila de Viaje',
    price: 49.99,
    description: 'Mochila resistente a la lluvia con múltiples bolsillos y diseño ergonómico.',
    category: 'electronics',
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    rating: { rate: 4.5, count: 145 },
  },
  {
    id: 15,
    title: 'Lámpara LED Multifunción',
    price: 27.5,
    description: 'Lámpara con control táctil, temperatura de color ajustable y puerto USB.',
    category: 'electronics',
    image: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
    rating: { rate: 4.4, count: 130 },
  },
  {
    id: 16,
    title: 'Smartphone Premium',
    price: 699.99,
    description: 'Smartphone de última generación con cámara profesional y batería de larga duración.',
    category: 'electronics',
    image: 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg',
    rating: { rate: 4.8, count: 180 },
  },
  {
    id: 17,
    title: 'Teclado Mecánico RGB',
    price: 89.99,
    description: 'Teclado gaming mecánico con switches rojos y iluminación RGB personalizable.',
    category: 'electronics',
    image: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
    rating: { rate: 4.5, count: 95 },
  },
  {
    id: 18,
    title: 'Monitor 4K Ultra HD',
    price: 349.99,
    description: 'Monitor profesional 4K con panel IPS y frecuencia de actualización de 144Hz.',
    category: 'electronics',
    image: 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg',
    rating: { rate: 4.7, count: 75 },
  },

  // Jewelery (6 productos)
  {
    id: 19,
    title: 'Reloj Minimalista',
    price: 89.9,
    description: 'Reloj elegante con correa de acero inoxidable ideal para cualquier outfit.',
    category: 'jewelery',
    image: 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg',
    rating: { rate: 4.9, count: 80 },
  },
  {
    id: 20,
    title: 'Anillo de Plata Fina',
    price: 24.99,
    description: 'Anillo minimalista con acabado pulido para eventos especiales.',
    category: 'jewelery',
    image: 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg',
    rating: { rate: 4.7, count: 45 },
  },
  {
    id: 21,
    title: 'Collar de Perlas',
    price: 59.99,
    description: 'Collar elegante de perlas cultivadas con cierre de oro.',
    category: 'jewelery',
    image: 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg',
    rating: { rate: 4.6, count: 60 },
  },
  {
    id: 22,
    title: 'Pulsera de Oro Blanco',
    price: 149.99,
    description: 'Pulsera delicada de oro blanco con diseño moderno.',
    category: 'jewelery',
    image: 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg',
    rating: { rate: 4.8, count: 35 },
  },
  {
    id: 23,
    title: 'Pendientes de Diamante',
    price: 299.99,
    description: 'Pendientes sofisticados con diamantes genuinos.',
    category: 'jewelery',
    image: 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg',
    rating: { rate: 4.9, count: 25 },
  },
  {
    id: 24,
    title: 'Broche Vintage',
    price: 39.99,
    description: 'Broche de estilo vintage con detalles en plata.',
    category: 'jewelery',
    image: 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg',
    rating: { rate: 4.4, count: 50 },
  },

  // Home & Garden (6 productos)
  {
    id: 25,
    title: 'Set de Jardinería Completo',
    price: 45.99,
    description: 'Kit completo con herramientas esenciales para el cuidado del jardín.',
    category: 'home & garden',
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    rating: { rate: 4.3, count: 120 },
  },
  {
    id: 26,
    title: 'Maceta Cerámica Moderna',
    price: 19.99,
    description: 'Maceta de cerámica con diseño minimalista para interiores.',
    category: 'home & garden',
    image: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
    rating: { rate: 4.1, count: 85 },
  },
  {
    id: 27,
    title: 'Cortinas Blackout',
    price: 34.99,
    description: 'Cortinas térmicas que bloquean completamente la luz.',
    category: 'home & garden',
    image: 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg',
    rating: { rate: 4.5, count: 95 },
  },
  {
    id: 28,
    title: 'Lámpara de Mesa Nórdica',
    price: 79.99,
    description: 'Lámpara de mesa con diseño escandinavo y luz cálida.',
    category: 'home & garden',
    image: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
    rating: { rate: 4.6, count: 70 },
  },
  {
    id: 29,
    title: 'Alfombra de Algodón',
    price: 89.99,
    description: 'Alfombra tejida a mano con fibras naturales.',
    category: 'home & garden',
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    rating: { rate: 4.4, count: 65 },
  },
  {
    id: 30,
    title: 'Set de Velas Aromáticas',
    price: 24.99,
    description: 'Velas naturales con aromas relajantes de lavanda y vainilla.',
    category: 'home & garden',
    image: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
    rating: { rate: 4.2, count: 110 },
  },

  // Sports & Outdoors (6 productos)
  {
    id: 31,
    title: 'Bicicleta de Montaña',
    price: 599.99,
    description: 'Bicicleta todo terreno con suspensión delantera y frenos de disco.',
    category: 'sports & outdoors',
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    rating: { rate: 4.7, count: 45 },
  },
  {
    id: 32,
    title: 'Mancuernas Ajustables',
    price: 149.99,
    description: 'Set de mancuernas con pesos ajustables de 5kg a 25kg.',
    category: 'sports & outdoors',
    image: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
    rating: { rate: 4.5, count: 85 },
  },
  {
    id: 33,
    title: 'Colchoneta de Yoga',
    price: 39.99,
    description: 'Colchoneta antideslizante de TPE ecológico de 6mm de grosor.',
    category: 'sports & outdoors',
    image: 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg',
    rating: { rate: 4.3, count: 120 },
  },
  {
    id: 34,
    title: 'Botella de Agua Deportiva',
    price: 19.99,
    description: 'Botella térmica de acero inoxidable con boquilla deportiva.',
    category: 'sports & outdoors',
    image: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
    rating: { rate: 4.1, count: 150 },
  },
  {
    id: 35,
    title: 'Raqueta de Tenis Profesional',
    price: 199.99,
    description: 'Raqueta de carbono con cordaje profesional para competición.',
    category: 'sports & outdoors',
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    rating: { rate: 4.6, count: 35 },
  },
  {
    id: 36,
    title: 'Tienda de Campaña 2 Personas',
    price: 129.99,
    description: 'Tienda ligera y resistente al agua para camping.',
    category: 'sports & outdoors',
    image: 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg',
    rating: { rate: 4.4, count: 60 },
  },

  // Books (4 productos)
  {
    id: 37,
    title: 'Guía de Programación React',
    price: 49.99,
    description: 'Libro completo sobre desarrollo con React y mejores prácticas.',
    category: 'books',
    image: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
    rating: { rate: 4.8, count: 90 },
  },
  {
    id: 38,
    title: 'Novela de Ciencia Ficción',
    price: 14.99,
    description: 'Historia futurista sobre viajes espaciales y aventuras.',
    category: 'books',
    image: 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg',
    rating: { rate: 4.2, count: 140 },
  },
  {
    id: 39,
    title: 'Libro de Cocina Saludable',
    price: 29.99,
    description: 'Recetas saludables con ingredientes naturales y consejos nutricionales.',
    category: 'books',
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    rating: { rate: 4.5, count: 75 },
  },
  {
    id: 40,
    title: 'Manual de Fotografía Digital',
    price: 39.99,
    description: 'Guía completa para principiantes en fotografía digital.',
    category: 'books',
    image: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
    rating: { rate: 4.3, count: 55 },
  },
];
